/* Offline product preview. No fetch, storage, telemetry, model calls or external effects. */
(function () {
  'use strict';
  const templates = {
    offer: {label:'Offer clarity',objective:'Help me turn my business idea into a clear offer for one specific customer.',title:'Clarify one offer before building more.',summary:'This example narrows the audience, the problem and a promise that can be checked.',steps:['Name one customer and the specific problem you want to solve.','Draft a short offer: audience, useful outcome and clear boundaries.','List the assumptions to check before you make a public promise.'],artifact:'For [specific customer] who struggles with [specific problem], we help them [useful outcome].\n\nThe first deliverable is [bounded result]. We will judge it by [observable evidence].\n\nStill to check: demand, feasibility and the cost of delivery.',stop:'Stop after one editable offer brief and an assumptions list. Do not contact customers, set a binding price or publish.',team:['Vera','Mira','Quinn','Gage']},
    website: {label:'Website review',objective:'Help me make my website clearer for someone visiting for the first time.',title:'Make the first visit easier to understand.',summary:'This example concentrates on the first screen and one primary action. It does not inspect a live website.',steps:['Write down who the page is for and what they should understand first.','Draft a headline, a short explanation and one primary action.','Review the draft for unsupported claims, confusing links and mobile clarity.'],artifact:'Headline: [A useful outcome for a specific person]\n\nExplanation: [What you provide, in one plain sentence]\n\nPrimary action: [One honest next step]\n\nReview question: Can a new visitor explain the offer without being coached?',stop:'Stop at a proposed first-screen rewrite and review checklist. No site is fetched, edited or published.',team:['Mira','Drew','Gage']},
    week: {label:'First-week plan',objective:'Help me choose a practical first week of work for my new business idea.',title:'Choose a first week that teaches you something.',summary:'This example makes a small plan around one uncertainty, one draft and a review point.',steps:['Choose the one uncertainty that most affects the next decision.','Prepare a small artifact that would make the idea easier to evaluate.','Set a review question and decide what evidence would justify continuing.'],artifact:'Focus: [The assumption we need to understand]\n\nFirst draft: [A small, reviewable artifact]\n\nReview question: [What did we learn?]\n\nContinue only if: [Evidence that supports another bounded step]',stop:'Stop at a first-week planning brief. Do not schedule work, send messages, spend money or claim the plan has been executed.',team:['Vera','Drew','Reed','Gage']}
  };
  let brief = null;
  const $ = id => document.getElementById(id);
  const make = (tag,cls,text) => {const n=document.createElement(tag);n.className=cls||'';n.textContent=text;return n;};
  const announce = text => {$('announcement').textContent=text;};
  function renderBrief() {
    const chosen=brief||{objective:templates.offer.objective,template:'offer'};
    const t=templates[chosen.template];
    $('brief-objective').textContent=chosen.objective;
    $('brief-subtitle').textContent=brief?'Your objective, placed in a fixed example template. No AI work has run.':'A fixed example of how an objective becomes a bounded piece of work.';
    $('template-label').textContent='EXAMPLE TEMPLATE / '+t.label.toUpperCase();
    $('brief-title').textContent=t.title;$('brief-summary').textContent=t.summary;
    $('work-steps').replaceChildren(...t.steps.map(s=>make('li','',s)));
    $('artifact-text').textContent=t.artifact;$('stop-condition').textContent=t.stop;
    $('proposed-team').replaceChildren(...t.team.map(name=>{const member=window.JoinermillRoster.find(p=>p.name===name);const row=make('div','suggested-person','');row.append(make('span','person-initial',name[0]));const text=make('div','',name);text.append(make('small','',member?member.role:'Specialist'));row.append(text);return row;}));
    $('brief-tag').textContent=brief?'Local':'Sample';
  }
  function navigate(focus=false){const key=location.hash.slice(1)||'workspace';const view=['workspace','brief','team','about'].includes(key)?key:'workspace';document.querySelectorAll('.view').forEach(n=>n.hidden=n.id!=='view-'+view);document.querySelectorAll('nav a').forEach(a=>{if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(view==='brief')renderBrief();document.title=(view==='workspace'?'Eva’s desk':view==='brief'?'Work brief':view==='team'?'The organization':'How it works')+' — EvaOS by Joinermill';if(focus){$('main').focus({preventScroll:true});window.scrollTo(0,0);}}
  function updateCount(){$('character-count').textContent=$('objective').value.length+' / 600';$('objective-error').hidden=true;$('objective').removeAttribute('aria-invalid');}
  $('objective').addEventListener('input',updateCount);
  document.querySelectorAll('[data-starter]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.starter;$('objective').value=templates[type].objective;$('template').value=type;updateCount();$('objective').focus();announce('Starting point added. You can edit it before previewing.');}));
  $('objective-form').addEventListener('submit',event=>{event.preventDefault();const value=$('objective').value.trim();if(value.length<12||value.length>600){$('objective-error').textContent='Add a little more direction: use 12–600 characters.';$('objective-error').hidden=false;$('objective').setAttribute('aria-invalid','true');$('objective').focus();return;}brief={objective:value,template:$('template').value};renderBrief();location.hash='brief';announce('Local example brief created. No work has been executed.');});
  $('reset-preview').addEventListener('click',()=>{brief=null;$('objective-form').reset();updateCount();renderBrief();location.hash='workspace';announce('Preview reset. Your objective has been cleared.');});
  $('download-brief').addEventListener('click',()=>{const b=brief||{objective:templates.offer.objective,template:'offer'};const t=templates[b.template];const content=['JOINERMILL / EVAOS — LOCAL PREVIEW BRIEF','Fixed example. No AI execution, specialist dispatch or server save.','', 'YOUR OBJECTIVE',b.objective,'','TEMPLATE: '+t.label,t.title,t.summary,'','PROPOSED WORK',...t.steps.map((s,i)=>(i+1)+'. '+s),'','SAMPLE DRAFT',t.artifact,'','PROPOSED ROLES (not assigned)',t.team.join(', '),'','STOP CONDITION',t.stop].join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='joinermill-preview-brief.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Brief downloaded to your device. Nothing was sent to a server.');});
  $('team-grid').replaceChildren(...window.JoinermillRoster.map(person=>{const card=make('article','person-card','');card.append(make('span','person-initial',person.name[0]),make('h3','',person.name),make('p','person-role',person.role),make('p','person-description',person.description));const details=document.createElement('details');details.append(make('summary','','Responsibility boundary'),make('p','',person.boundary));card.append(details);return card;}));
  $('roster-count').textContent=window.JoinermillRoster.length+' named specialists';
  $('roster-note').textContent='Directory only. No presence feed, live assignments or background activity is connected to this preview.';
  window.addEventListener('hashchange',()=>navigate(true));renderBrief();navigate();
})();
